//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRommSys.Client.Web.ControlService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OptionType", Namespace="http://schemas.datacontract.org/2004/07/ShowRoomSys.Service")]
    public enum OptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Start = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Previous = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Next = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastDoc = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NextDoc = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Play = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pause = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stop = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullScreen = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncreaseZoom = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecreaseZoom = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoveUp = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoveDown = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoveLeft = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoveRight = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        End = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlService.IMainControl", CallbackContract=typeof(ShowRommSys.Client.Web.ControlService.IMainControlCallback))]
    public interface IMainControl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainControl/RegisterClient", ReplyAction="http://tempuri.org/IMainControl/RegisterClientResponse")]
        void RegisterClient(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainControl/Option1", ReplyAction="http://tempuri.org/IMainControl/Option1Response")]
        void Option1(ShowRommSys.Client.Web.ControlService.OptionType option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainControl/Option2", ReplyAction="http://tempuri.org/IMainControl/Option2Response")]
        void Option2(ShowRommSys.Client.Web.ControlService.OptionType option, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainControl/Option3", ReplyAction="http://tempuri.org/IMainControl/Option3Response")]
        void Option3(ShowRommSys.Client.Web.ControlService.OptionType option, string ID, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainControl/GetOnLineStatus", ReplyAction="http://tempuri.org/IMainControl/GetOnLineStatusResponse")]
        string GetOnLineStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainControlCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMainControl/SendMessage")]
        void SendMessage(ShowRommSys.Client.Web.ControlService.OptionType type);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMainControl/SendMessages")]
        void SendMessages(ShowRommSys.Client.Web.ControlService.OptionType type, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainControlChannel : ShowRommSys.Client.Web.ControlService.IMainControl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainControlClient : System.ServiceModel.DuplexClientBase<ShowRommSys.Client.Web.ControlService.IMainControl>, ShowRommSys.Client.Web.ControlService.IMainControl {
        
        public MainControlClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MainControlClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MainControlClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainControlClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MainControlClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegisterClient(string ID) {
            base.Channel.RegisterClient(ID);
        }
        
        public void Option1(ShowRommSys.Client.Web.ControlService.OptionType option) {
            base.Channel.Option1(option);
        }
        
        public void Option2(ShowRommSys.Client.Web.ControlService.OptionType option, string ID) {
            base.Channel.Option2(option, ID);
        }
        
        public void Option3(ShowRommSys.Client.Web.ControlService.OptionType option, string ID, string fileName) {
            base.Channel.Option3(option, ID, fileName);
        }
        
        public string GetOnLineStatus() {
            return base.Channel.GetOnLineStatus();
        }
    }
}
